### ISSUE TITLE
references static library project link not updated

### ISSUE THREAD

**Issue by fatmingwang** [nokotan/VSExtForEmscripten#32]
Thank you for this project save me a lot of time.

I got 2 problems please help me

First
    I have some references static library project, After I built static library project(library file ooxx.a not been updated ) then 
    compile startup project, Nothing changed still got previous ooxx.a result ,I have to delete ooxx.a file and compile startup project 
    again to make it link correctly, Is this a bug or I got  something wrong?
Second 
   How to make debugger works?
   The output show failed to launch debug adapter 'wasm-chrome'
   Then it popup a dialog  Unable to start program
   "E:\Work\emsdk\upstream\emscripten\emrun.bat"
   the specific working directory does not exists or is not a full path.

This my project link
https://github.com/fatmingwang/FishGame
http://152.67.205.106/FishGame/

Thanks.

**Comment by nokotan** [comment]
First:

Perhaps your projects dependencies have not been configured properly, which leads to build the start-up project before finishing to build the static library projects. 

Please refer to <https://learn.microsoft.com/en-us/visualstudio/ide/how-to-create-and-remove-project-dependencies?view=vs-2022> to configure your projects dependencies.

Second:

Which version of the emscripten extension is used for your project? The emscripten extension v0.6.x are broken due to the breaking changes introduced in v0.7.0.
